version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: www_backend:latest
    container_name: www_backend_container
    env_file: .env
    restart: on-failure
    ports:
      - 8000:8000
