services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: www_backend
    env_file: .env
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 1
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - ./logs:/app/www_project/logs
