name: EC2 Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull eshun/wwm-backend:v1.0

      - name: Delete Old docker container
        run: sudo docker rm -f wwm-back || true

      - name: Run Docker container
        run: sudo docker run -d -p 9000:8000 --name wwm-back eshun/wwm-backend:v1.0
