name: EC2 Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH In EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP_ADDRESS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/projects

      - name: Pull Docker image
        run: sudo docker pull eshun/wwm-backend:v1.0

      - name: Delete Old docker container
        run: sudo docker system prune --force

      - name: Compose Up
        run: docker-compose up -d wwm-backend
