name: Production CI/CD

on:
  push:    
    branches: ["**"]

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.18.0"

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/production' || github.ref == 'refs/heads/main'
    steps:
      - name: SSH into EC2 Instance and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST_IP_ADDRESS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /home/ubuntu/scripts && \
            if [ "${{ github.ref }}" = "refs/heads/production" ]; then
              sudo ./deploy-wwm-prod.sh
            else
              sudo ./deploy-wwm.sh
            fi



# name: Production CI/CD

# on:
#   push:
#     branches: ["production", "main"]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: SSH In EC2 Instance
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.PROD_HOST_IP_ADDRESS }}
#           username: ${{ secrets.EC2_USERNAME }}
#           key: ${{ secrets.PROD_SSH_KEY }}
#           script: |
#             cd /home/ubuntu/scripts && \
#             if [ "${{ github.ref }}" = "refs/heads/production" ]; then
#               sudo ./deploy-wwm-prod.sh
#             else
#               sudo ./deploy-wwm.sh
#             fi
